/* Focused browser/rendering QC. Requires an installed Playwright + Chromium. */
const {chromium} = require(process.env.KORA_PLAYWRIGHT_MODULE || "playwright");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const base = process.argv[2] || "http://127.0.0.1:8794";
const output = process.argv[3] || "/tmp/kora-hero-browser-qc";
const url = new URL(base);
assert(["127.0.0.1","localhost"].includes(url.hostname) && url.protocol === "http:", "localhost only");
fs.mkdirSync(output,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1080}});
 const page=await context.newPage();
 const errors=[], external=[];
 page.on("pageerror",e=>errors.push(e.message));
 page.on("console",m=>{if(m.type()==="error")errors.push(m.text());});
 page.on("request",r=>{if(new URL(r.url()).origin!==url.origin)external.push(r.url());});
 const checks=[];
 const state=()=>page.evaluate(()=>window.koraHeroState);
 const step=()=>page.locator("#step").click();
 const waitReady=()=>page.waitForFunction(()=>!document.querySelector("#step").disabled);
 await page.goto(base+"/hero"); await waitReady();
 assert.equal(await page.locator(".task").count(),0);
 await step();
 assert.equal(await page.locator("#memory").innerText(),"—");
 await step();
 assert.equal(await page.locator("#memory").innerText(),"32 GiB");
 assert.equal(await page.locator("#footprint").innerText(),"18 GiB");
 assert.equal(await page.locator(".candidate").count(),0);
 await step(); await step();
 assert.equal(await page.locator(".candidate").count(),4);
 assert.equal(await page.locator("#selected").innerText(),"MLX-LM");
 for(let i=4;i<17;i++)await step();
 await page.screenshot({path:path.join(output,"desktop-running.png"),fullPage:true,animations:"disabled"});
 const before=await state();
 const history=await page.locator("#history").innerText();
 await page.reload(); await waitReady();
 assert.deepEqual(await state(),before);
 assert.equal(await page.locator("#history").innerText(),history);
 checks.push("reload restores complete projection, outputs, event cursor and history");
 const api=await (await context.request.get(base+"/api/hero/events")).json();
 assert.deepEqual(before,api.frames[before.event.sequence]);
 checks.push("browser state equals canonical server frame");
 await page.locator("#play").click();
 await page.waitForFunction(()=>window.koraHeroState?.event.sequence>17);
 await page.locator("#play").click();
 const paused=(await state()).event.sequence;
 await page.waitForTimeout(800);
 assert.equal((await state()).event.sequence,paused);
 checks.push("play advances events and pause freezes cursor");
 while((await state()).event.sequence<api.event_count-1)await step();
 assert.equal(await page.locator("#outcome").innerText(),"Accepted · fixture");
 assert.equal(await page.locator("[data-lane] .task").count(),4);
 assert((await page.locator("#answer").innerText()).includes("Launch brief"));
 assert((await page.locator("#quality").innerText()).includes("fixture_pass"));
 await page.screenshot({path:path.join(output,"desktop-accepted.png"),fullPage:true,animations:"disabled"});
 await page.reload();
 await page.waitForFunction(()=>window.koraHeroState?.projection.run_state==="completed");
 assert.deepEqual(await state(),api.frames.at(-1));
 checks.push("accepted fixture requires service gate and survives completed reload");
 await page.locator("#scenario").selectOption("quality-failed");await waitReady();
 const failedApi=await (await context.request.get(base+"/api/hero/events?scenario=quality-failed")).json();
 for(let i=0;i<failedApi.event_count;i++)await step();
 assert.equal(await page.locator("#outcome").innerText(),"Not accepted · fixture");
 assert.equal((await state()).view.structural_acceptance,"fixture_pass");
 assert.equal((await state()).view.service_acceptance,"fixture_fail");
 await page.screenshot({path:path.join(output,"desktop-quality-rejected.png"),fullPage:true,animations:"disabled"});
 checks.push("quality failure blocks acceptance after all tasks and merge complete");
 await page.locator("#scenario").selectOption("unknown");await waitReady();
 for(let i=0;i<6;i++)await step();
 assert.equal(await page.locator("#selected").innerText(),"No selection");
 assert.equal(await page.locator(".task").count(),0);
 assert.equal(await page.locator("#outcome").innerText(),"Not accepted · fixture");
 checks.push("unknown overhead fails closed before task creation");
 // Simulate SSE connection failure; the ordered JSON endpoint restores the queue.
 await page.route("**/api/hero/sse?*",route=>route.abort());
 await page.locator("#scenario").selectOption("pc");await waitReady();
 await page.waitForFunction(()=>document.querySelector("#transport").textContent.includes("Recovered"));
 for(let i=0;i<4;i++)await step();
 assert.equal(await page.locator("#selected").innerText(),"llama.cpp");
 assert.equal(await page.locator("#memory").innerText(),"8 GiB");
 assert((await page.locator("#memory-detail").innerText()).includes("32 GiB"));
 assert((await page.locator('[data-adapter="llama.cpp"]').innerText()).includes("placement_requires_runtime_plan"));
 checks.push("SSE failure recovers via bounded event endpoint with PC fixture reasons");
 await page.unroute("**/api/hero/sse?*");
 // Reload starts paused, even with a reduced-motion preference.
 await page.emulateMedia({reducedMotion:"reduce"});
 await page.locator("#scenario").selectOption("apple");await waitReady();
 for(let i=0;i<13;i++)await step();
 const motion=await page.locator(".task").first().evaluate(el=>getComputedStyle(el).animationName);
 assert.equal(motion,"none");
 await page.locator("#step").focus();await page.keyboard.press("Enter");
 assert.equal((await state()).event.sequence,13);
 checks.push("reduced motion removes animations; keyboard event stepping works");
 for(const viewport of [{width:1440,height:1080},{width:1024,height:768},{width:390,height:844}]){
   await page.setViewportSize(viewport);
   assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),"horizontal overflow");
   for(const id of ["play","step","reset","scenario"]){
     const box=await page.locator("#"+id).boundingBox();assert(box && box.width>20 && box.x>=0 && box.x+box.width<=viewport.width+1,id+" clipped");
   }
 }
 await page.screenshot({path:path.join(output,"mobile-reduced-motion.png"),fullPage:true,animations:"disabled"});
 checks.push("desktop, tablet and mobile: no horizontal overflow or clipped controls");
 await page.setViewportSize({width:1440,height:1080});
 await page.goto(base+"/");
 await page.waitForFunction(()=>window.koraStudioScriptStatus?.status==="ready");
 const run=page.locator('[data-kora-keyboard-contract="primary-run-local-harness"]');
 await run.click();
 await page.waitForFunction(()=>document.querySelector("#kora-primary-result-status")?.textContent==="completed");
 assert.equal(await page.locator('a[href="/hero"]').count(),1);
 checks.push("existing Studio and local deterministic harness preserved");
 // An aborted fixture SSE request is intentional in this check.
 const unexpected=errors.filter(e=>!e.includes("ERR_FAILED"));
 assert.deepEqual(unexpected,[]);
 assert.deepEqual(external,[]);
 const result={ok:true,checks,unexpected_console_errors:unexpected,external_requests:external,
   scope:"Automated browser/rendering QC; no human visual review or service-quality measurement."};
 fs.writeFileSync(path.join(output,"browser-qc.json"),JSON.stringify(result,null,2)+"\n");
 console.log(JSON.stringify(result,null,2));
 await browser.close();
})().catch(error=>{console.error(error);process.exitCode=1;});
